name: Fire Agent
on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Build data (FIRMS counts + windy key if provided)
        env:
          FIRMS_KEY: ${{ secrets.FIRMS_KEY }}
          WINDY_KEY: ${{ secrets.WINDY_KEY }}
        run: |
          python scripts/build_data.py
      - name: Copy site to docs and commit
        run: |
          mkdir -p docs
          cp index.html docs/index.html
          cp -r static docs/static || true
          git config user.name "fire-agent"
          git config user.email "fire-agent@users.noreply.github.com"
          git add docs
          git commit -m "ci: refresh docs (data + site)" || echo "no changes to commit"
          git push
